
services:
  livekit-client:
    build: ../
    ports:
      - "5173:5173"
    restart: unless-stopped
    volumes:
      - ../src:/app/src
      - ../public:/app/public

  livekit-auth:
    build: ./
    command: ["./livekit-auth-server"]
    environment:
      LIVEKIT_API_KEY: ${LIVEKIT_API_KEY}
      LIVEKIT_API_SECRET: ${LIVEKIT_API_SECRET}
      LIVEKIT_HOST_URL: ${LIVEKIT_HOST_URL}
    ports:
      - "8080:8080"
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    command: start --all --config /etc/ngrok.yml
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml:ro
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    depends_on:
      - livekit-auth
      - livekit-client

